version: 2

models:
  - name: stg_students
    columns:
      - name: student_id
        description: "student id"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "first name"        
      - name: last_name
        description: "last name"
      - name: building
        description: "building"
      - name: school_district
        description: "school district"
      - name: grade
        description: "grade"
      - name: gender
        description: "gender"
      - name: language
        description: "language"
      - name: dob
        description: "dob"